In [1]:
import numpy as np

In [2]:
A = np.array([[1, -1, 0.1],
              [2, -2, 0.2]])
A

array([[ 1. , -1. ,  0.1],
       [ 2. , -2. ,  0.2]])

In [3]:
AT = A.T
AT

array([[ 1. ,  2. ],
       [-1. , -2. ],
       [ 0.1,  0.2]])

In [4]:
W = np.array([[3, 5, 7, 9],
              [4, 6, 8, 0]])
W

array([[3, 5, 7, 9],
       [4, 6, 8, 0]])

In [5]:
Z = np.matmul(AT, W)
Z

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [  1.1,   1.7,   2.3,   0.9]])

In [6]:
# another way to call the matmul function is by using `@`
Z2 = AT @ W
Z2

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [  1.1,   1.7,   2.3,   0.9]])

In [7]:
AT = np.array([[200, 17]])
W = np.array([[1, -3, 5],
              [-2, 4, -6]])
b = np.array([[-1, 1, 2]])

In [8]:
def dense(AT, W, b):
    z = np.matmul(AT, W) + b
    a_out = g(z)
    return a_out
